### ISSUE TITLE
will not delete before update entry

### ISSUE THREAD

**Issue by mircea-mihail** [Costinteo/shellsec#2]
I installed shellsec before it had the delete feature and entered a dummy password for "cana" to test it out. Today I decided to move all my passwords to shellsec and to remove the dummy "cana" one, but, though the updated shellsec allows me to remove new entries, it will not allow me to remove "cana". I even tried to make a new "cana" entry, and i was able to remove it, but the former "cana" is unremovable.
The error message is "No password found for platform cana!".

**Comment by Costinteo** [comment]
Hello!
Thanks for reporting this. I've narrowed down the issue after some digging and realized that saving platforms under a multi-word name will mess up with the function that prints all platforms. The function currently looks like this:

```bash
printAllPlatforms() {
    [ ! -f "$SECRET_FILE" ] && printError "No password file found!" && return 1
    cat "$SECRET_FILE" | grep -oP --color=none -- "^[^:\s]+"
}
```

You can see the problem in the grep regex, it selects everything except ``:`` and ``\s``. Changing the regex to only read up until ``:`` should fix the issue. Working on it!
